### ISSUE TITLE
Grammatical errors in README.md

### ISSUE THREAD

**Issue by Akshit6828** [kcoder63/SuperMaxioCheckers_snakes-hackers#28]
Hi @starlightknown. There are some grammatical errors in the file [README.md][file1]  as explained below :
> * `Thanks goes` -> `Thanks go`
The singular verb `goes` does not appear to agree with the plural subject `Thanks`. Thus, Considered changing the verb form for subject-verb agreement.

> * `Contributions of any kind welcome!` -> `Contributions of any kind are welcome!`
Should use the appropriate form of the verb. 

### PS: Well it was a lovely game to play ❤️ 

[file1]:(https://github.com/starlightknown/SuperMaxioCheckers_snakes-hackers#readme)

**Comment by Akshit6828** [comment]
Please check #29. 😃

**Comment by GaryHilares** [comment]
I'm not sure if 'Thanks goes to' is actually a gramatical error. [Here](https://english.stackexchange.com/questions/15429/which-is-correct-special-thanks-go-to-or-special-thanks-goes-to) there is a question where they asked about a very similar situation and althought many people said that 'Thanks go' is what one would expect, 'thanks goes' is also widely used. Additionally, that text comes from the [All Contributors project](https://github.com/all-contributors/all-contributors) and was inserted by the [All Contributors bot](https://github.com/all-contributors/app). If it is an error, it should also be addressed there.

I think that the second sentence, 'Contributions of any kind welcome!', isn't a gramatical error because 'welcome' is an adjective and, therefore, doesn't need the verb 'to be' to qualify the noun. However, I'm not an expert in English so I'm not sure if this is correct.

**Comment by Akshit6828** [comment]
Ok, thanks for the feedback @GaryNLOL. 
Actually, I crosschecked it on [textranch][link1]. So it corrected me when I was checking the documentation as like this:

![checkthanks](https://user-images.githubusercontent.com/57808363/121910070-28c2dd80-cd4c-11eb-99b3-9ee11d1afc7b.png)


Also for the '**Contributions of any kind welcome**', I got a correction in Google Docs as shown below:

![Typo](https://user-images.githubusercontent.com/57808363/121910335-63c51100-cd4c-11eb-82b9-6b9ab88e608c.png)


I am sorry for this if it's not correct. You can close the PR and the issue too.

Thanks for the feedback @GaryNLOL. 😃 




[link1]:https://textranch.com/revisions/1231812/?access_key=a4c6531405a3#
